services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  App\:
    resource: '../src/{EventListener}'

  App\EventListener\ApiListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -1 }
