imports:
    - {resource: listeners.yaml}
    - {resource: repositories.yaml}
    - {resource: controllers.yaml}

parameters:
    locale: en
    base_url: '%env(BASE_URL)%'
    env(REDIS_URL): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/{Services,Repository,Command,DataFixtures}'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]

    Predis\ClientInterface:
        class: Predis\Client
        arguments:
            $parameters: '%env(REDIS_URL)%'
